on:
  push:
    branches:
      - main

jobs:
  run_terraform_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Terraform Job
        uses: ../jobs/deploy-infrastructure.yml
